### ISSUE TITLE
So why do you call it fast? 

### ISSUE THREAD

**Issue by antonmedv** [jmhodges/jsonpp#16]
It has same speed as Go `json` packages. And why you claimed it fast?

**Comment by jmhodges** [comment]
Because it's faster than other platform's general JSON decoding (the static buffer is handy, too).

**Comment by antonmedv** [comment]
I can't just prepend "fast" to all your Go libs. Claiming something "fast", just because it's written in Go and not dynamic/intepereted language is same as claiming "blazing fast" in js.

**Comment by jmhodges** [comment]
The speed is pretty good and is faster than the tools most folks use.

These comments have given me an opportunity to write down some things I think I’ll be able to use again in the future. I hope they end up helpful to you.

You’re frustrated by documentation for some random codebase written by someone you don’t know. (And it’s possible  you also don’t use this codebase?) Somehow that documentation has left you upset enough that you decided to leave odd, negative comments. But why does this matter that much to you? And what do the comments gain you?

How did this project and this topic become important enough to bother interacting with, you know?

I know from my own experience that we often do things like leaving negative comments on random projects because we’re feeling bad about something else. Usually, I didn’t realize that I was feeling bad beforehand! Sometimes an embarrassing memory had resurfaced, or a conversation had gone poorly, or maybe I just hadn’t eaten enough all day. These things would escalate my negative emotions with all sorts of topics that I’d never be very bothered with before.

Taking the time to consider what I’ve been thinking about in the moments before I interact with a stranger in frustration has helped me immensely.

I hope you have a good day

**Comment by antonmedv** [comment]
You right, another day I skip something like this. 

![](https://imgs.xkcd.com/comics/duty_calls.png)
